### ISSUE TITLE
consider python standard library's strtobool for boolean casting

### ISSUE THREAD

**Issue by arahayrabedian** [rconradharris/envparse#6]
Hey, I notice the code for boolean casting comes from a limited set of hard-coded strings, I've recently become aware of a python-standard [strtobool](https://docs.python.org/2/distutils/apiref.html#distutils.util.strtobool), I believe the only one missing would be "ok".

Would you object to a small PR migrating to that?

**Comment by LynnCo** [comment]
bumping, since this seems like a good addition

**Comment by rconradharris** [comment]
A couple of things to consider with this change:

1. `ok` is allowable in the existing code and wouldn't be allowable in the refactored version
2. Anything that's not truthy is considered falsy in the existing code; in the refactored version 'falsy' values are well-defined and anything that's not truthy or falsy raises a ValueError.
3. `strtobool` actually doesn't convert to a `bool`, it actually converts to an integer of 0 or 1 (probably because it predates the `bool` datatype.

The main issues here are 1) and 2) since they lead to backwards incompatible changes. So even this this would be a nice cleanup, thinking on balance, it's not worth it at the moment.
