### ISSUE TITLE
Mirror os.environ by allowing Env to be accessed like a dictionary

### ISSUE THREAD

**Issue by lynncyrin** [rconradharris/envparse#7]
Would involve: 
- mapping a `Env.__getitem__` function that maps to `Env.__call__`
- a `Env.__dict__` that outputs schema values
- a `Env.__str__` prints out dict

**Comment by rconradharris** [comment]
@LynnCo Thanks for the suggestion here! I'm somewhat hesitant to add this feature since it'll introduce another parallel API for interacting with `envparse`, one using `__call__` and the other `__getitem__`. At least in a minor version upgrade.

Perhaps this suggestion could be implemented in an `envparse 1.0` release.

If the schema was required to be defined up-front (which it currently isn't), then the limitation of the dictionary-API would be nearly as bad, and we could probably make it work.

**Comment by frankwiles** [comment]
Another option would be to provide a `get()` method that could work like:

```
foo = env.get('FOO', False)
```

With `False` being the default if it doesn't exist. This is honestly something I expected in the library and was sort of surprised when I didn't find it.

**Comment by coilysiren** [comment]
I'm closing a bunch of my older github issues ♻️  feel free to open a new issue describing this same change! Or re-open this one, if someone is still interested in working on it 📝
